image: starefossen/ruby-node:latest

variables:
  JEKYLL_ENV: production
  NODE_ENV: production

before_script:
  - bundle install
  - npm install

after_script:
  - rm -r .git typings node_modules
  - find . -type f \( -name \*.ts -o -name \*.jade -o -name \*.scss \) -delete

build:
  stage: build
  artifacts:
    expire_in: 30min
    paths:
      - .
  script:
    - npx sass --sourcemap=none --update .
    - npx tsc -p tsconfig.json || true

test:
  stage: test
  dependencies:
    - build
  except:
    - master
  script:
    - bundle exec jekyll build -d test
  artifacts:
    expire_in: 30min
    paths:
      - test

pages:
  stage: deploy
  dependencies:
    - build
  only:
    - master
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public

stages:
  - build
  - test
  - deploy
