image: starefossen/ruby-node:latest

variables:
  JEKYLL_ENV: production
  NODE_ENV: production

before_script:
  - bundle install
  - npm install

after_script:
  - find . -type d \( -path ./assignments -o -path ./classwork \) -prune -o -exec rm -r "{}" \;
  - find . -type f \( -name \*.html -o -name \*.css -o -name \*.js \) -prune -o -empty -delete

build:
  stage: build
  artifacts:
    expire_in: 30min
    paths:
      - .
  script:
    - npm run build

test:
  stage: test
  dependencies:
    - build
  except:
    - master
  script:
    - bundle exec jekyll build -d test
  artifacts:
    expire_in: 30min
    paths:
      - test

pages:
  stage: deploy
  dependencies:
    - build
  only:
    - master
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public

stages:
  - build
  - test
  - deploy
