---
  image: starefossen/ruby-node:latest

  variables:
    JEKYLL_ENV: production
    NODE_ENV: production

  before_script:
    - bundle install

  build:
    stage: build
    artifacts:
      expire_in: 1d
      paths:
        - .
    before_script:
      - bundle install
      - npm install --production
    script:
      - npm run build
    after_script:
      - find . -mindepth 1 -maxdepth 1 \( -path ./nodejs -o -path ./assignments -o -path ./classwork -o -name _config.yml \) -prune -o -exec rm -rf "{}" \;
      - find . -mindepth 1 \( -path \*/fonts\* -o -path \*/images\* -o -name \*.html -o -name \*.css -o -name \*.js -o -name _config.yml \) -prune -o -type f -exec rm -f "{}" \;

  test:
    stage: test
    dependencies:
      - build
    except:
      - master
    artifacts:
      expire_in: 30min
      paths:
        - test
    script:
      - bundle exec jekyll build -d test

  pages:
    stage: deploy
    dependencies:
      - build
    only:
      - master
    artifacts:
      paths:
        - public
    script:
      - bundle exec jekyll build -d public

  stages:
    - build
    - test
    - deploy
