image: starefossen/ruby-node:latest

variables:
  JEKYLL_ENV: production
  NODE_ENV: production

before_script:
  - bundle install

build:
  stage: build
  artifacts:
    expire_in: 1d
    paths:
      - .
  before_script:
    - npm install
  script:
    - npm run build
  after_script:
    - find . -type d \( -path ./assignments -o -path ./classwork \) -prune -o -exec rm -rf "{}" \; || true
    - find . -type f \( -path \*/images\* -o -name \*.html -o -name \*.css -o -name \*.js \) -prune -o -exec rm -f "{}" \;

test:
  stage: test
  dependencies:
    - build
  except:
    - master
  artifacts:
    expire_in: 30min
    paths:
      - test
  script:
    - bundle exec jekyll build -d test

pages:
  stage: deploy
  dependencies:
    - build
  only:
    - master
  artifacts:
    paths:
      - public
  script:
    - bundle exec jekyll build -d public

stages:
  - build
  - test
  - deploy
