extends: stylelint-config-standard
plugins:
  - stylelint-no-unsupported-browser-features
rules:
  # Possible Errors
  color-no-invalid-hex: true
  font-family-no-duplicate-names: true
  function-calc-no-unspaced-operator: true
  # Stylistic Issues
  string-quotes: double
  block-opening-brace-newline-before: always
  block-opening-brace-space-before: null
  # Plugin Configuration
  plugin/no-unsupported-browser-features:
    - true
    - browsers:
      - Chrome >= 1
      - Firefox >= 3.5
      - IE >= 9.0
      - Opera >= 10
      - Safari >= 3.2
      ignore: []
