extends:
  - stylelint-config-standard
  - stylelint-config-sass-guidelines
plugins:
  - stylelint-no-unsupported-browser-features
rules:
  color-no-invalid-hex: true
  font-family-no-duplicate-names: true
  function-calc-no-unspaced-operator: true
  plugin/no-unsupported-browser-features:
    - true
    - browsers:
      - defaults
      ignore: []
