---
  extends:
    - stylelint-config-standard
    - stylelint-config-sass-guidelines
  plugins:
    - stylelint-no-unsupported-browser-features
  rules:
    at-rule-no-unknown:
      - true
      - ignoreAtRules:
        - extend
    block-opening-brace-newline-after: 'always'
    block-closing-brace-newline-before: 'always'
    declaration-block-no-duplicate-properties: true
    declaration-block-no-shorthand-property-overrides: true
    declaration-colon-space-after: 'always' # always-single-line
    font-family-no-duplicate-names: true
    function-calc-no-unspaced-operator: true
    function-comma-space-after: 'always' # always-single-line
    function-linear-gradient-no-nonstandard-direction: true
    max-empty-lines: 1
    selector-class-pattern:
      - '[a-z]{2,3}-[A-z]+(_[A-z]+)?(-[a-z]+)?'
      - message: 'Selector should be written ECSS style (selector-class-pattern)'
    selector-list-comma-newline-after: 'always-multi-line'
    selector-max-universal: 0
    plugin/no-unsupported-browser-features:
      - true
      - browsers:
          # Desktop
          - "last 2 Chrome versions"
          - "last 2 Edge versions"
          - "Explorer >= 11"
          - "last 2 Firefox versions"
          # Mobile
          - "last 2 Android versions"
          - "last 2 ChromeAndroid versions"
          - "last 2 ExplorerMobile versions"
          - "last 2 FirefoxAndroid versions"
          - "last 2 iOS versions"
          - "last 2 Safari versions"
        ignore: []
    scss/dollar-variable-pattern:
      - '[A-z]+'
    scss/percent-placeholder-pattern:
      - '[a-z]{2,3}-[A-z]+(_[A-z]+)?(-[a-z]+)?'
      - message: 'Selector should be written ECSS style (scss/percent-placeholder-pattern)'
